"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import setuptools

APP = ['offload/gui.py']
DATA_FILES = ['offload/data',
    # 'offload/data/report_template.html', 'offload/data/fonts/SourceSans3-Bold.otf',
              #           'offload/data/fonts/SourceSans3-BoldIt.otf', 'offload/data/fonts/SourceSans3-It.otf',
              #           'offload/data/fonts/SourceSans3-Light.otf', 'offload/data/fonts/SourceSans3-LightIt.otf',
              #           'offload/data/fonts/SourceSans3-Regular.otf'
              ]
OPTIONS = {'iconfile': 'offload/data/offload.icns'}

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=[
        'xxhash',
        'pyqt5',
        'psutil',
        'pillow'
    ],
    name="Offload",  # Replace with your own username
    version="0.1b",
    author="Caffeine Creations",
    author_email="contact@caffeine-creations.com",
    description="Transfer files",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/thejoltjoker/offload",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: MacOS",
    ],
    python_requires='>=3.9',
)
